# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dora.yaml.j2

dora:
  fullnameOverride: dora
  image:
    repository: ethpandaops/dora
    tag: master
    pullPolicy: Always
  ingress:
    enabled: true
    className: ingress-nginx-public
    hosts:
      - host: dora.kaustinen-testnet.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

  name: kaustinen-testnet
  configPath: "https://config.kaustinen-testnet.ethpandaops.io/cl/config.yaml"
  validatorNamesInventory: "https://config.kaustinen-testnet.ethpandaops.io/api/v1/nodes/validator-ranges"

  postgresql:
    name: "dora-postgresql"
    fullnameOverride: "dora-postgresql"
  
  endpoints:
  # Rpc
  - url: http://teku-geth-001:5052
    name: rpc-teku-geth-001
    archive: true
    priority: 1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.bootnode-1.srv.kaustinen-testnet.ethpandaops.io
    name: bootnode-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lodestar-geth-1.srv.kaustinen-testnet.ethpandaops.io
    name: lodestar-geth-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lodestar-geth-10.srv.kaustinen-testnet.ethpandaops.io
    name: lodestar-geth-10
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lodestar-geth-2.srv.kaustinen-testnet.ethpandaops.io
    name: lodestar-geth-2
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lodestar-geth-3.srv.kaustinen-testnet.ethpandaops.io
    name: lodestar-geth-3
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lodestar-geth-4.srv.kaustinen-testnet.ethpandaops.io
    name: lodestar-geth-4
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lodestar-geth-5.srv.kaustinen-testnet.ethpandaops.io
    name: lodestar-geth-5
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lodestar-geth-6.srv.kaustinen-testnet.ethpandaops.io
    name: lodestar-geth-6
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lodestar-geth-7.srv.kaustinen-testnet.ethpandaops.io
    name: lodestar-geth-7
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lodestar-geth-8.srv.kaustinen-testnet.ethpandaops.io
    name: lodestar-geth-8
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lodestar-geth-9.srv.kaustinen-testnet.ethpandaops.io
    name: lodestar-geth-9
    priority: -1
