# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/ethereum-node.yaml.j2

lodestar-geth-001:
  global:
    main:
      network: verkle-gen-devnet-3
      engineEndpoint: http://geth-lodestar-001:8551
      rpcEndpoint: http://geth-lodestar-001:8545
      beaconEndpoint: http://lodestar-geth-001:5052
    checkpointSync:
      enabled: false
      addresses:
        verkle-gen-devnet-3: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.teku-nethermind-1.verkle-gen-devnet-3.ethpandaops.io
    clientArgs:
      networks:
        verkle-gen-devnet-3:
          execution:
            besu:
            nethermind:
            geth:
              - --http.api=eth,net,web3,debug,admin,personal
              - --http.vhosts=*
              - --networkid=69421
              - --syncmode=full
              - --bootnodes=enode://31b85eee78794e712f05902180740a608051b5bd8e7993c089e5f94d5d924c0f3530815ab4fb2ca4c1dedbb2a7c00c0817fd3588830791ccc34bb1bfd3e2442c@49.12.202.109:30303?discport=30303
              - --rpc.allow-unprotected-txs
              - --cache.preimages
              - --override.prague=1706865900
              - --rpc.allow-unprotected-txs
            erigon:
            ethereumjs:
          consensus:
            lodestar:
              - --paramsFile=/data/network-config/config.yaml
              - --genesisStateFile=/data/network-config/genesis.ssz
              - --bootnodes=enr:-Iq4QK-W9Lflp78TpPAWzyYz9z01jC38PnjNOlyzfFEgZAHMFvng1k2DGTvjY17KJDaZmAGPEQwVI2JM6OcBMweIV1uGAY1pDUMbgmlkgnY0gmlwhDEMym2Jc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIyk,enr:-MS4QJ0T0CvI9DonrcFWvN5w_32ro5GhFS6xcJvwqp2GRYTWSLdi80cR2T_vSa3FcSOpRuY-M4qeuyAeOGAOPPR_z6oEh2F0dG5ldHOIAAMAAAAAAACEZXRoMpDgt7j9UIBiVyChBwAAAAAAgmlkgnY0gmlwhDEMym2Jc2VjcDI1NmsxoQMhmuodzYqxT_LCuDZJffCmvPeI1kf7t2bQodLx76LuMohzeW5jbmV0c4gAAAAAAAAAAIN0Y3CCIyiDdWRwgiMo
              - --rest.namespace="*"
              - --network.connectToDiscv5Bootnodes
              - --nat=true
            teku:
              - --Xepochs-store-blobs=max # Keep the blobs forever
            prysm:
            lighthouse:
              - --testnet-dir=/data/network-config
              - --boot-nodes=enr:-Iq4QK-W9Lflp78TpPAWzyYz9z01jC38PnjNOlyzfFEgZAHMFvng1k2DGTvjY17KJDaZmAGPEQwVI2JM6OcBMweIV1uGAY1pDUMbgmlkgnY0gmlwhDEMym2Jc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIyk,enr:-MS4QJ0T0CvI9DonrcFWvN5w_32ro5GhFS6xcJvwqp2GRYTWSLdi80cR2T_vSa3FcSOpRuY-M4qeuyAeOGAOPPR_z6oEh2F0dG5ldHOIAAMAAAAAAACEZXRoMpDgt7j9UIBiVyChBwAAAAAAgmlkgnY0gmlwhDEMym2Jc2VjcDI1NmsxoQMhmuodzYqxT_LCuDZJffCmvPeI1kf7t2bQodLx76LuMohzeW5jbmV0c4gAAAAAAAAAAIN0Y3CCIyiDdWRwgiMo
              - --debug-level=debug
              - --prune-payloads=false
              - --reconstruct-historic-states
            nimbus:


  geth:
    enabled: true
    fullnameOverride: geth-lodestar-001
    image:
      repository: ethpandaops/geth
      tag: kaustinen-with-shapella-linux-amd64
      pullPolicy: Always
    p2pNodePort:
      enabled: false
    persistence:
      enabled: true
      size: 100Gi
    podLabels:
      network: verkle-gen-devnet-3
      testnet: verkle-gen-devnet-3
      ethereum_network: verkle-gen-devnet-3
      ethereum_role: execution
      consensus_client: lodestar
      execution_client: geth
      ethereum_instance: geth-lodestar-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    initContainers:
      - name: init-config
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            CHAINSPEC_URI=https://config.verkle-gen-devnet-3.ethpandaops.io/el/chainspec.json;
            GENESIS_URI=https://config.verkle-gen-devnet-3.ethpandaops.io/el/genesis.json;
            BESU_GENESIS_URI=https://config.verkle-gen-devnet-3.ethpandaops.io/el/besu.json;
            BOOTNODES_URI=https://config.verkle-gen-devnet-3.ethpandaops.io/el/bootnodes.txt;
            TRUSTED_SETUP_URI=https://config.verkle-gen-devnet-3.ethpandaops.io/trusted_setup.txt;
            mkdir -p /data/network-config;
            if ! [ -f /data/network_config_init_done ];
            then
              apk update && apk add curl jq;
              wget -O /data/network-config/chainspec.json $CHAINSPEC_URI;
              wget -O /data/network-config/genesis.json $GENESIS_URI;
              wget -O /data/network-config/besu.json $BESU_GENESIS_URI;
              wget -O /data/network-config/bootnodes.txt $BOOTNODES_URI;
              wget -O /data/network-config/trusted_setup.txt $TRUSTED_SETUP_URI;
              cat /data/network-config/genesis.json | jq -r '.config.chainId' > /data/network-config/chainid.txt;
              touch /data/network_config_init_done;
              echo "network config init done";
            else
              echo "network config already present";
            fi;
            echo "bootnode init done: $(cat /data/network-config/bootnodes.txt)";
        volumeMounts:
          - name: storage
            mountPath: "/data"
      - name: init-genesis
        image: ethpandaops/geth:kaustinen-with-shapella-linux-amd64
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            if ! [ -f /data/genesis_init_done ];
            then
              geth init --state.scheme=path --datadir /data /data/network-config/genesis.json;
              touch /data/genesis_init_done;
              echo "genesis init done";
            else
              echo "genesis is already initialized";
            fi;
        volumeMounts:
          - name: storage
            mountPath: "/data"

  lodestar:
    enabled: true
    fullnameOverride: lodestar-geth-001
    image:
      repository: ethpandaops/lodestar
      tag: g11tech-verge-815364b
      pullPolicy: Always
    mode: "beacon"
    p2pNodePort:
      enabled: false
    podLabels:
      network: verkle-gen-devnet-3
      testnet: verkle-gen-devnet-3
      ethereum_network: verkle-gen-devnet-3
      ethereum_role: consensus
      consensus_client: lodestar
      execution_client: geth
      ethereum_instance: lodestar-geth-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    persistence:
      enabled: true
      size: 200Gi
    initContainers:
    - name: init-genesis
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      command:
        - sh
        - -ace
        - >
          apk add jq curl sed;
          DEPOSIT_CONTRACT_URI=https://config.verkle-gen-devnet-3.ethpandaops.io/deposit_contract.txt;
          DEPOSIT_CONTRACT_BLOCK_URI=https://config.verkle-gen-devnet-3.ethpandaops.io/cl/deposit_contract_block.txt;
          DEPLOY_BLOCK_URI=https://config.verkle-gen-devnet-3.ethpandaops.io/cl/deploy_block.txt;
          GENESIS_CONFIG_URI=https://config.verkle-gen-devnet-3.ethpandaops.io/cl/config.yaml;
          GENESIS_SSZ_URI=https://config.verkle-gen-devnet-3.ethpandaops.io/cl/genesis.ssz;
          mkdir -p /data/network-config;
          curl -s https://config.verkle-gen-devnet-3.ethpandaops.io/api/v1/nodes/inventory | jq -r '.ethereum_pairs[] | .consensus.enr' > /data/network-config/bootnodes.txt;
          TRUSTED_SETUP_URI=https://config.verkle-gen-devnet-3.ethpandaops.io/trusted_setup.txt;
          if ! [ -f /data/network-config/genesis.ssz ];
          then
            wget -O /data/network-config/deposit_contract.txt $DEPOSIT_CONTRACT_URI;
            wget -O /data/network-config/deposit_contract_block.txt $DEPOSIT_CONTRACT_BLOCK_URI;
            wget -O /data/network-config/deploy_block.txt $DEPLOY_BLOCK_URI;
            wget -O /data/network-config/config.yaml $GENESIS_CONFIG_URI;
            wget -O /data/network-config/genesis.ssz $GENESIS_SSZ_URI;
            wget -O /data/network-config/trusted_setup.txt $TRUSTED_SETUP_URI;
            echo "genesis init done";
          else
            echo "genesis exists. skipping...";
          fi;
          (tr '\n' ',' < /data/network-config/bootnodes.txt | sed 's/[^,]*/"&"/g') > /data/network-config/bootnodes2.txt;
          mv /data/network-config/bootnodes2.txt /data/network-config/bootnodes.txt;
          echo "bootnode init done: $(cat /data/network-config/bootnodes.txt)";
      volumeMounts:
        - name: storage
          mountPath: "/data"
