# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/blobscan.yaml.j2

blobscan:
  fullnameOverride: blobscan
  image:
    repository: blossomlabs/blobscan
    tag: latest
    pullPolicy: Always
  ingress:
    enabled: true
    className: ingress-nginx-public
    hosts:
      - host: blobscan.verkle-hsf-0.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blobscan
                port:
                  number: 3000
  config:
    NEXTAUTH_URL: https://blobscan.verkle-hsf-0.ethpandaops.io
    NEXT_PUBLIC_NETWORK_NAME: verkle-hsf-0
    NEXT_PUBLIC_BEACON_BASE_URL: https://dora.verkle-hsf-0.ethpandaops.io
    NEXT_PUBLIC_EXPLORER_BASE_URL: https://explorer.verkle-hsf-0.ethpandaops.io
    BEACON_NODE_ENDPOINT: http://lodestar-geth-001:5052
    CHAIN_ID: "17000"
  blobscandb:
    fullnameOverride: blobscan-blobscandb

blobscan-indexer:
  fullnameOverride: blobscan-indexer
  image:
    repository: blossomlabs/blobscan-indexer
    tag: latest
    pullPolicy: Always
  config:
    EXECUTION_NODE_ENDPOINT: http://geth-lodestar-001:8545
    BEACON_NODE_ENDPOINT: http://lodestar-geth-001:5052

# Blobscan API
blobscan-api:
  fullnameOverride: blobscan-api
  image:
    repository: blossomlabs/blobscan
    tag: latest
    pullPolicy: Always
  config:
    BEACON_NODE_ENDPOINT: http://lodestar-geth-001:5052
    CHAIN_ID: "17000"
  ingress:
    enabled: true
    className: ingress-nginx-public
    hosts:
      - host: blobscan-api.verkle-hsf-0.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blobscan-api
                port:
                  number: 3001
