# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/ethereum-node.yaml.j2

lodestar-geth-001:
  global:
    main:
      network: verkle-gen-devnet-5
      engineEndpoint: http://geth-lodestar-001:8551
      rpcEndpoint: http://geth-lodestar-001:8545
      beaconEndpoint: http://lodestar-geth-001:5052
    checkpointSync:
      enabled: false
      addresses:
        verkle-gen-devnet-5: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.teku-nethermind-1.verkle-gen-devnet-5.ethpandaops.io
    clientArgs:
      networks:
        verkle-gen-devnet-5:
          execution:
            besu:
              - --genesis-file=/data/network-config/besu.json
              - --bootnodes=enode://d33e9f9072af3c504c6e1c82e3dae4cd79f865018447845e45ad58b640547943c9fd42f2968420a28a956f3383abd388b9432c688c980d50adca9472c4aae8c4@195.201.36.62:30303?discport=30303
              - --rpc-http-api=ADMIN,CLIQUE,MINER,ETH,NET,DEBUG,TXPOOL,ENGINE,TRACE,WEB3
              - --sync-mode=FULL
              - --data-storage-format=VERKLE
              - --network="kaustinen"
              - --ethstats=k8s-lodestar-geth-001:<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.verkle-devnets.ethstats_secret}>@ethstats.verkle-gen-devnet-5.ethpandaops.io:443
            nethermind:
            geth:
              - --http.api=eth,net,web3,debug,admin,personal
              - --http.vhosts=*
              - --networkid=69420
              - --syncmode=full
              - --bootnodes=enode://d33e9f9072af3c504c6e1c82e3dae4cd79f865018447845e45ad58b640547943c9fd42f2968420a28a956f3383abd388b9432c688c980d50adca9472c4aae8c4@195.201.36.62:30303?discport=30303
              - --rpc.allow-unprotected-txs
              - --cache.preimages
              - --override.prague=1711712640
              - --rpc.allow-unprotected-txs
            erigon:
            ethereumjs:
          consensus:
            lodestar:
              - --paramsFile=/data/network-config/config.yaml
              - --genesisStateFile=/data/network-config/genesis.ssz
              - --bootnodes=enr:-Iq4QFvNGYvVoO3Dwe7elUaubnzGYL5Gc18bkJI1kgi9Y6hBDZD4Apjxkkat5eh9HqiT1Rt25P0_sqlOggsMm7o8p62GAY6J9_5WgmlkgnY0gmlwhMPJJD6Jc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIyk,enr:-MS4QGkH8-3GtCPBtZ4lG9T1I3TvgNNJsN9CQMYASc6oKI3kAGGTLXsIaGiwpNgLnXfyH28hCi9KRO35OP7XZ4Tzho4Eh2F0dG5ldHOIDAAAAAAAAACEZXRoMpCoebm8UBFGCCChBwAAAAAAgmlkgnY0gmlwhMPJJD6Jc2VjcDI1NmsxoQLIBOt0y_TG73z6WylC3oFtL9Ouo_Kfu1AkOQcyGIBZzYhzeW5jbmV0c4gAAAAAAAAAAIN0Y3CCIyiDdWRwgiMo
              - --rest.namespace="*"
              - --network.connectToDiscv5Bootnodes
              - --nat=true
            teku:
              - --data-storage-mode=ARCHIVE
              - --Xepochs-store-blobs=max # Keep the blobs forever
            prysm:
            lighthouse:
              - --testnet-dir=/data/network-config
              - --boot-nodes=enr:-Iq4QFvNGYvVoO3Dwe7elUaubnzGYL5Gc18bkJI1kgi9Y6hBDZD4Apjxkkat5eh9HqiT1Rt25P0_sqlOggsMm7o8p62GAY6J9_5WgmlkgnY0gmlwhMPJJD6Jc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIyk,enr:-MS4QGkH8-3GtCPBtZ4lG9T1I3TvgNNJsN9CQMYASc6oKI3kAGGTLXsIaGiwpNgLnXfyH28hCi9KRO35OP7XZ4Tzho4Eh2F0dG5ldHOIDAAAAAAAAACEZXRoMpCoebm8UBFGCCChBwAAAAAAgmlkgnY0gmlwhMPJJD6Jc2VjcDI1NmsxoQLIBOt0y_TG73z6WylC3oFtL9Ouo_Kfu1AkOQcyGIBZzYhzeW5jbmV0c4gAAAAAAAAAAIN0Y3CCIyiDdWRwgiMo
              - --debug-level=debug
              - --prune-payloads=false
              - --reconstruct-historic-states
            nimbus:


  geth:
    enabled: true
    fullnameOverride: geth-lodestar-001
    image:
      repository: ethpandaops/geth
      tag: gballet-eip-4762-rewrite-44c1724
      pullPolicy: Always
    p2pNodePort:
      enabled: false
    persistence:
      enabled: true
      size: 100Gi
    podLabels:
      network: verkle-gen-devnet-5
      testnet: verkle-gen-devnet-5
      ethereum_network: verkle-gen-devnet-5
      ethereum_role: execution
      consensus_client: lodestar
      execution_client: geth
      ethereum_instance: geth-lodestar-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    initContainers:
      - name: init-config
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            CHAINSPEC_URI=https://config.verkle-gen-devnet-5.ethpandaops.io/el/chainspec.json;
            GENESIS_URI=https://config.verkle-gen-devnet-5.ethpandaops.io/el/genesis.json;
            BESU_GENESIS_URI=https://config.verkle-gen-devnet-5.ethpandaops.io/el/besu.json;
            BOOTNODES_URI=https://config.verkle-gen-devnet-5.ethpandaops.io/el/bootnodes.txt;
            mkdir -p /data/network-config;
            if ! [ -f /data/network_config_init_done ];
            then
              apk update && apk add curl jq;
              wget -O /data/network-config/chainspec.json $CHAINSPEC_URI;
              wget -O /data/network-config/genesis.json $GENESIS_URI;
              wget -O /data/network-config/besu.json $BESU_GENESIS_URI;
              wget -O /data/network-config/bootnodes.txt $BOOTNODES_URI;
              cat /data/network-config/genesis.json | jq -r '.config.chainId' > /data/network-config/chainid.txt;
              touch /data/network_config_init_done;
              echo "network config init done";
            else
              echo "network config already present";
            fi;
            echo "bootnode init done: $(cat /data/network-config/bootnodes.txt)";
        volumeMounts:
          - name: storage
            mountPath: "/data"
      - name: init-genesis
        image: ethpandaops/geth:gballet-eip-4762-rewrite-44c1724
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            if ! [ -f /data/genesis_init_done ];
            then
              geth --datadir /data --override.prague=1711712640 --cache.preimages init /data/network-config/genesis.json;
              touch /data/genesis_init_done;
              echo "genesis init done";
            else
              echo "genesis is already initialized";
            fi;
        volumeMounts:
          - name: storage
            mountPath: "/data"

  lodestar:
    enabled: true
    fullnameOverride: lodestar-geth-001
    image:
      repository: ethpandaops/lodestar
      tag: g11tech-verge-628c35a
      pullPolicy: Always
    mode: "beacon"
    p2pNodePort:
      enabled: false
    podLabels:
      network: verkle-gen-devnet-5
      testnet: verkle-gen-devnet-5
      ethereum_network: verkle-gen-devnet-5
      ethereum_role: consensus
      consensus_client: lodestar
      execution_client: geth
      ethereum_instance: lodestar-geth-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    persistence:
      enabled: true
      size: 200Gi
    initContainers:
    - name: init-genesis
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      command:
        - sh
        - -ace
        - >
          apk add jq curl sed;
          DEPOSIT_CONTRACT_URI=https://config.verkle-gen-devnet-5.ethpandaops.io/deposit_contract.txt;
          DEPOSIT_CONTRACT_BLOCK_URI=https://config.verkle-gen-devnet-5.ethpandaops.io/cl/deposit_contract_block.txt;
          DEPLOY_BLOCK_URI=https://config.verkle-gen-devnet-5.ethpandaops.io/cl/deploy_block.txt;
          GENESIS_CONFIG_URI=https://config.verkle-gen-devnet-5.ethpandaops.io/cl/config.yaml;
          GENESIS_SSZ_URI=https://config.verkle-gen-devnet-5.ethpandaops.io/cl/genesis.ssz;
          mkdir -p /data/network-config;
          curl -s https://config.verkle-gen-devnet-5.ethpandaops.io/api/v1/nodes/inventory | jq -r '.ethereum_pairs[] | .consensus.enr' > /data/network-config/bootnodes.txt;
          if ! [ -f /data/network-config/genesis.ssz ];
          then
            wget -O /data/network-config/deposit_contract.txt $DEPOSIT_CONTRACT_URI;
            wget -O /data/network-config/deposit_contract_block.txt $DEPOSIT_CONTRACT_BLOCK_URI;
            wget -O /data/network-config/deploy_block.txt $DEPLOY_BLOCK_URI;
            wget -O /data/network-config/config.yaml $GENESIS_CONFIG_URI;
            wget -O /data/network-config/genesis.ssz $GENESIS_SSZ_URI;
            echo "genesis init done";
          else
            echo "genesis exists. skipping...";
          fi;
          (tr '\n' ',' < /data/network-config/bootnodes.txt | sed 's/[^,]*/"&"/g') > /data/network-config/bootnodes2.txt;
          mv /data/network-config/bootnodes2.txt /data/network-config/bootnodes.txt;
          echo "bootnode init done: $(cat /data/network-config/bootnodes.txt)";
      volumeMounts:
        - name: storage
          mountPath: "/data"
