# role: ethpandaops.general.bootstrap
bootstrap_default_user_authorized_keys_github_team_el:
   - gballet
   - holiman
   - karalabe
   - g11tech

# role: ethpandaops.general.ethereum_node
ethereum_node_el: geth

# role: ethpandaops.general.geth
geth_container_name: execution
geth_container_image: "{{ default_ethereum_client_images.geth }}"
geth_container_env:
  VIRTUAL_HOST: "{{ ethereum_node_rcp_hostname }}"
  VIRTUAL_PORT: "{{ ethereum_node_el_ports_http_rpc | string }}"
  LETSENCRYPT_HOST: "{{ ethereum_node_rcp_hostname }}"
geth_container_command_extra_args:
#  - --holesky
  - --http.api=eth,net,web3,debug,admin,personal
  - --http.vhosts=*
  - --syncmode=full
  - --bootnodes={{ ethereum_el_bootnodes | join(',') }}
  - --rpc.allow-unprotected-txs
  - --cache.preimages
  - --override.prague=1706285288
  - --override.overlay-stride=10000
  - --override.blockproof=true
  - --clear.verkle.costs=true
  - --networkid={{ ethereum_network_id }}
geth_init_custom_network: false
geth_container_pull: true
