lodestar_container_command_extra_args:
  - --paramsFile=/network-config/config.yaml
  - --genesisStateFile=/network-config/genesis.ssz
  - --bootnodes={{ ethereum_cl_bootnodes | join(',') }}
  - --rest.namespace="*"
  - --network.connectToDiscv5Bootnodes
  - --nat=true
  - --checkpointSyncUrl=https://eth:g11techisntoneperson@bn.lodestar-geth-9.srv.kaustinen-testnet.ethpandaops.io