- hosts: all,!localhost
  roles:
    - role: ethpandaops.general.beacon_stopper
      tags: [script, beacon_stopper]

- hosts: all
  become: true
  roles:
    - role: state_fetcher
      tags: [state_fetcher]

# Unpacks the state, will not run if the folder already has pre-existing state in it
# Note: this tag assumes the state has already been fetched, please ensure that the state_fetcher
# has been given enough time to complete
- hosts: all
  become: true
  tags: [state_unpack]
  tasks:
    - name: unpack state
      unarchive:
        src: "{{ state_fetcher_datadir }}/{{ state_fetcher_s3_key }}"
        dest: "{{ state_fetcher_unpack_dir }}"
        creates: "{{ state_fetcher_unpack_dir }}/{{ ethereum_node_el }}"
        remote_src: yes
        extra_opts: [--strip-components=1]

- hosts: all
  become: true
  roles:
    - role: ethpandaops.general.geth
      tags: [node]

- hosts: all,!localhost
  serial: "{{ batch_count | default('100%') }}"
  tags: [cleanup]
  become: true
  tasks:
    - name: Cleanup all data
      block:
        - name: Remove eth containers
          community.docker.docker_container:
            name: "{{ item }}"
            state: absent
            timeout: 5
          loop:
            # Consensus layer clients
            - "lighthouse-validator"
            - "lighthouse"
            - "lodestar-validator"
            - "lodestar"
            - "nimbus"
            - "prysm-validator"
            - "prysm"
            - "teku-validator"
            - "teku"
            - "beacon"
            - "validator"
        - name: Remove data dirs
          file:
            state: absent
            path: "{{ item }}"
          loop:
            # Consensus layer data
            - /data/lighthouse
            - /data/lighthouse-validator
            - /data/lodestar
            - /data/lodestar-validator
            - /data/nimbus
            - /data/nimbus-validator
            - /data/prysm
            - /data/prysm-validator
            - /data/teku
            - /data/teku-validator

